remote_theme: jakartaee/jekyll-theme-jakarta-ee
#theme: jekyll-theme-jakarta-ee

title: [Jakarta EE TCK]
description: [Source code and resources to build and run the Jakarta EE TCK suite]

links:
  source: https://github.com/eclipse-ee4j/jakartaee-tck
  download: https://download.eclipse.org/ee4j/jakartaee-tck
  faq: https://eclipse-ee4j.github.io/jakartaee-tck/wiki
  Jakarta EE 9.1: https://eclipse-ee4j.github.io/jakartaee-tck/wiki/9.1.x
  mailinglist: https://accounts.eclipse.org/mailing-list/jakartaee-tck-dev
